#! /usr/bin/env python

###################################################################
# LOAD THE ENVIRONMENT AND SET UP THE TOOLS
###################################################################

## We assume that 'bksys' is our admin directory
import sys, os
sys.path.append('bksys')

## Import the main configuration tool
from generic import configure
config = {
	'modules'  : 'generic qt4',
#	'builddir' : 'build', # put all object files under './'
	'config.h' : 0,
	'rpath'    : 1,
	'bootstrap': 1,
	'colorful' : not os.environ.has_key('NOCOLORS'),
}

# and the config.h
env=configure(config)

###################################################################
# SCRIPTS FOR BUILDING THE TARGETS
###################################################################

env.BuildDir('#build', 'base', duplicate=0)
env.subdirs("build")

###################################################################
# CONVENIENCE FUNCTIONS TO EMULATE 'make dist' and 'make distclean'
###################################################################

# if you forget to add a version number, the one in the file VERSION will be used instead
env.dist('ovis', '1.0.1')

