#! /usr/bin/env python
## This script demonstrates how to build and install
## a simple kde program having KconfigXT settings
## with scons
##
## Thomas Nagy, 2004, 2005

## This file can be reused freely for any project (see COPYING)

## Use the environment and the tools set in the top-level
## SConstruct file (set with 'Export') - this is very important

Import( 'env' )

obj=env.qt4obj('program', env)
obj.target='../build/ovis'
obj.source="""
main.cpp
mainwindow.cpp
mainglwidget.cpp
"""
obj.cxxflags='-DQT_THREAD_SUPPORT'
obj.uselib='QT QTCORE QTOPENGL'
#obj.libs='QtCore QtGui QtOpenGL ovisbase ovisvideo ovismath'
obj.libs='ovisbase ovisvideo ovismath ovisopengl'
obj.includes=['.','/usr/include/qt4','/usr/include/qt4/QtCore','/usr/include/qt4/QtGui','/usr/include/qt4/QtOpenGL']
obj.instdir='/usr/local/bin'
obj.libpaths=['#build']
obj.linkflags='-Wl,-rpath=.'
obj.execute()
