#! /usr/bin/env python
## This script demonstrates how to build and install
## a simple kde program having KconfigXT settings
## with scons
##
## Thomas Nagy, 2004, 2005

## This file can be reused freely for any project (see COPYING)

############################
## load the config

## Use the environment and the tools set in the top-level
## SConstruct file (set with 'Export') - this is very important

Import( 'env' )

obj=env.genobj('shlib', env)
obj.target='video'
obj.libprefix='../build/lib'
obj.source="""
attributebuffer.cpp
attributetable.cpp
camera.cpp
caps.cpp
channeldatatype.cpp
cubemap.cpp
indexiterator.cpp
indexstream.cpp
light.cpp
lightlist.cpp
memindexstream.cpp
memvertexstream.cpp
occlusionquery.cpp
picbuffer.cpp
pixelformat.cpp
pixmap.cpp
program.cpp
propertynode.cpp
propertytable.cpp
renderer.cpp
scenenode.cpp
simplelightserver.cpp
simplepicbuffer.cpp
testcube.cpp
testtorus.cpp
texture2d.cpp
texture.cpp
transformnode.cpp
vertexformat.cpp
vertexiterator.cpp
vertexstream.cpp
videodevice.cpp
visitorqueue.cpp
"""
#obj.cxxflags='-DQT_THREAD_SUPPORT'
obj.uselib=''
obj.libs='base math'
obj.includes='.'
obj.instdir='/usr/local/lib'
obj.libpaths=['#build']
obj.execute()
