__revision__ = "src/engine/SCons/Node/Python.py 0.96.91 2005/10/17 20:04:26 ita"
import SCons.Node
class Value(SCons.Node.Node):
    """A class for Python variables, typically passed on the command line 
    or generated by a script, but not from a file or some other source.
    """
    def __init__(self, value):
        SCons.Node.Node.__init__(self)
        self.value = value
    def __str__(self):
        return repr(self.value)
    def build(self):
        """A "builder" for Values."""
        pass
    current = SCons.Node.Node.children_are_up_to_date
    def is_under(self, dir):
        return 1
    def get_contents(self):
        """The contents of a Value are the concatenation
        of all the contents of its sources with the node's value itself."""
        contents = str(self.value)
        for kid in self.children(None):
            contents = contents + kid.get_contents()
        return contents
    def get_csig(self, calc=None):
        """Because we're a Python value node and don't have a real
        timestamp, we get to ignore the calculator and just use the
        value contents."""
        try:
            binfo = self.binfo
        except AttributeError:
            binfo = self.binfo = self.new_binfo()
        try:
            return binfo.ninfo.csig
        except AttributeError:
            binfo.ninfo.csig = self.get_contents()
            self.store_info(binfo)
            return binfo.ninfo.csig
