#! /usr/bin/env python
## This script demonstrates how to build and install
## a simple kde program having KconfigXT settings
## with scons
##
## Thomas Nagy, 2004, 2005

## This file can be reused freely for any project (see COPYING)

############################
## load the config

## Use the environment and the tools set in the top-level
## SConstruct file (set with 'Export') - this is very important

Import( 'env' )

#env.BuildDir('build', 'base', duplicate=0)

obj=env.genobj('shlib', env)
obj.target='ovisbase'
obj.libprefix='../build/lib'
obj.source="""
basememobj.cpp
datablock.cpp
fpscalc.cpp
localfile.cpp
localstreamable.cpp
log.cpp
managedmemobj.cpp
nullstream.cpp
numericarrays.cpp
pkdatablock.cpp
refcounted.cpp
stdoutstream.cpp
streamable.cpp
string.cpp
stringlist.cpp
timer.cpp
"""

if env['WINDOWS'] == 1:
    obj.source+="dynobject_win32.cpp"
else:
    obj.source+="dynobject_unix.cpp"

obj.cxxflags='-DOVIS_EXPORTS'
obj.uselib=''
#obj.libs='dl z bz2'
obj.libs='dl'
obj.includes='.'
obj.instdir='/usr/local/lib'
obj.execute()
