#! /usr/bin/env python
## This script demonstrates how to build and install
## a simple kde program having KconfigXT settings
## with scons
##
## Thomas Nagy, 2004, 2005

## This file can be reused freely for any project (see COPYING)

############################
## load the config

## Use the environment and the tools set in the top-level
## SConstruct file (set with 'Export') - this is very important

Import( 'env' )

env.BuildDir('build', 'base', duplicate=0)

obj=env.genobj('shlib', env)
obj.target='base'
#obj.libprefix='../build/lib'
obj.source="""
basememobj.cpp
bz2pkhandler.cpp
datablock.cpp
dynobject_unix.cpp
fpscalc.cpp
localfile.cpp
localstreamable.cpp
log.cpp
managedmemobj.cpp
nullstream.cpp
numericarrays.cpp
pkdatablock.cpp
refcounted.cpp
stdoutstream.cpp
streamable.cpp
string.cpp
stringlist.cpp
timer.cpp
zpkhandler.cpp
"""
#obj.cxxflags='-DQT_THREAD_SUPPORT'
obj.uselib=''
obj.libs='dl z bz2'
obj.includes='.'
obj.instdir='/usr/local/lib'
obj.execute()
